---
- name: Create Jenkins API token and secret text credential
  hosts: localhost
  gather_facts: false
  vars:
    JENKINS_URL: "http://127.0.0.1:8080"
    SONARQUBE_URL: "http://127.0.0.1:9000"
    JENKINS_USERNAME: "admin"
    JENKINS_PASSWORD: "password"

  pre-tasks:
    - name: Wait for SonarQube to be up
      uri:
        url: "{{ SONARQUBE_URL }}/api/system/status"
      register: sonarqube_status
      until: sonarqube_status.json.status == "UP"
      retries: 60
      delay: 10
      when: sonarqube_status.status != 200

    vars:
      file: ../sonar_config/deploy_sonarqube.yaml
  
  tasks:
    - name: Create Jenkins secret text credential
      uri:
        url: "{{ JENKINS_URL }}/credentials/store/system/domain/_/createCredentials"
        method: POST
        user: "{{ JENKINS_USERNAME }}"
        password: "{{ JENKINS_PASSWORD }}"
        body_format: json
        body:
          '':
            '0'
          credentials:
            scope: GLOBAL
            id: "sonarqube-token"
            secret: "{{ SONARQUBE_TOKEN }}"
            description: "SonarQube User Token"
            stapler-class: "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
            '$class': "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
      register: result_create_credential
      failed_when: result_create_credential.status != 200
