---
- name: Download and Deploy Petclinic App to pcapp
  hosts: pcapp
  gather_facts: false
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  tasks:
    - name: Download Petclinic.jar
      shell: "curl http://jenkins:8080//job/PetClinicBuild/1/artifact/target/spring-petclinic-3.1.0-SNAPSHOT.jar -o ~/spring-petclinic-3.1.0-SNAPSHOT.jar"
      args:
        warn: false

    - name: Start PetClinic Application
      command: "/usr/bin/java -jar /root/spring-petclinic-3.1.0-SNAPSHOT.jar --server.port=8085 &"
      async: 0
      poll: 0

    - name: Wait for PetClinic Application to Start
      wait_for:
        host: pcapp
        port: 8085
        timeout: 300
      ignore_errors: yes

    - name: Print Access URL
      debug:
        msg: "PetClinic Deployed, access at http://localhost:8085"
