- name: Deploy and Run Petclinic App
  hosts: pcapp
  gather_facts: false
  tasks:
    - name: Download Petclinic.jar
      shell: "curl http://jenkins:8080//job/PetClinicBuild/1/artifact/target/spring-petclinic-3.1.0-SNAPSHOT.jar -o /root/spring-petclinic-3.1.0-SNAPSHOT.jar"
      args:
        warn: false

    - name: Start PetClinic Application
      command: "/root/pc_deploy/pc_service.sh"
      async: 0
      poll: 0

    - name: Wait for PetClinic Application to Start
      wait_for:
        host: localhost
        port: 8085
        timeout: 300
      ignore_errors: yes

    - name: Print Access URL
      debug:
        msg: "PetClinic Deployed, access at http://localhost:8085"
