version: '3.3'

services:
  #Jenkins Container Variables
  jenkins:
    image: jenkins/jenkins:jdk17
    volumes:
      - jenkins_config/casc.yaml:/var/jenkins_home/casc.yaml
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
    networks:
      - devnet
    ports:
      - '8080:8080'
      - '8084:8084'
      - '50000:50000'

    environment:
      #Set Jenkins Installation Options
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true

      #Set Jenkins Environment Variables
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      
    build:
      context: .
      dockerfile: jenkins_config/Dockerfile
    
  #Sonarqube Container Variables
  sonarqube:
    image: sonarqube:9.9-community

    networks:
      - devnet
    ports:
      - '9000:9000'
    depends_on:
      - db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
    build:
      context: .
      dockerfile: jenkins_config/Dockerfile
  
  #Sonarqube Database Container Variables
  db:
    image: postgres
    networks:
      - devnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube

networks:
  devnet:
    driver: bridge