---
- name: Deploy Jenkins with Configuration as Code
  hosts: localhost

  vars:
    JENKINS_URL: "http://127.0.0.1:8080"
    JENKINS_USERNAME: "admin"
    JENKINS_PASSWORD: "password"
    PLUGINS_FILE: "plugins.txt"
    JOB_FILE: "./pc_job.xml"
    JOB_NAME: "PetClinicBuild"

  tasks: 
    - name: Read content of pc_job.xml
      slurp:
        path: "{{ JOB_FILE }}"
      register: job_config_content

    - name: Create Jenkins Job
      jenkins_job:
        url: "{{ JENKINS_URL }}"
        user: "{{ JENKINS_USERNAME }}"
        password: "{{ JENKINS_PASSWORD }}"
        name: "{{ JOB_NAME }}"
        config: "{{ job_config_content['content'] | b64decode }}"
      register: result

    - name: Check Jenkins Job Creation Status
      debug:
        var: result