---
- name: Create Jenkins API token and secret text credential
  hosts: localhost
  gather_facts: false
  vars:
    JENKINS_URL: "http://127.0.0.1:8080"
    SONARQUBE_URL: "http://127.0.0.1:9000"
    JENKINS_USERNAME: "admin"
    JENKINS_PASSWORD: "password"
    JOB_NAME: "PetClinicBuild"

  tasks: 
    - name: Trigger Jenkins job
      uri:
        url: "{{ JENKINS_URL }}/job/{{ JOB_NAME }}/build"
        method: POST
        user: "{{ JENKINS_USERNAME }}"
        password: "{{ JENKINS_PASSWORD }}"
        status_code: 201
      register: trigger_result
      until: trigger_result.status == 201
      retries: 10
      delay: 10
      ignore_errors: yes

    - name: Check build status
      uri:
        url: "{{ JENKINS_URL }}/job/{{ JOB_NAME }}/lastBuild/api/json"
        user: "{{ JENKINS_USERNAME }}"
        password: "{{ JENKINS_PASSWORD }}"
        return_content: yes
      register: build_status_result
      retries: 30
      delay: 10
      until: build_status_result is succeeded
      ignore_errors: yes

    - name: Display build status
      debug:
        msg: "Build is still in progress."
      when: build_status_result.json.building | bool | default(false) and build_status_result.json.inProgress | bool | default(true)
      retries: 60
      delay: 10
      until: not(build_status_result.json.building | bool | default(false) and build_status_result.json.inProgress | bool | default(true))

    - name: Build is complete
      debug:
        msg: "Build is complete."
      when: not(build_status_result.json.building | bool | default(false) and build_status_result.json.inProgress | bool | default(true))




